
version: '3'
services:
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./data:/var/lib/clickhouse
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data